# validate-changes-update-db.yaml
# Author: Pete Pickerill
# Description:
#   This flow runs several Liquibase commands to generate information that could be useful for review, auditing
#   and troubleshooting purposes.  It will run in all shared pipeline environments from CI onward. It is not
#   required in development environments

stages:
  validateChangelog:
    # Run validate on Repo Changelog
    # https://docs.liquibase.com/commands/update/validate.html
    actions:
      - type: liquibase
        command: validate
        cmdArgs: {}

      # Show database status
      # https://docs.liquibase.com/commands/change-tracking/status.html
      - type: liquibase
        command: status
        cmdArgs: { changelog-file: "${LIQUIBASE_COMMAND_CHANGELOG_FILE}", verbose: "true" }

      # Run Checks on Repo Changelog
      # https://docs.liquibase.com/commands/quality-checks/subcommands/run.html
      - type: liquibase
        command: checks run
        cmdArgs:
          { changelog-file: "${LIQUIBASE_COMMAND_CHANGELOG_FILE}",
            checks-scope: "changelog",
            checks-settings-file: "s3://${AWS_S3_BUCKET}/static/checks/liquibase.checks-settings.conf"
          }

  # generateUpdateInfo:
  #   actions:
  #     - type: liquibase
  #       # Run everywhere but DEV
  #       if: "${LIQUIBASE_FLOW_ENV} != DEV"
  #       # https://docs.liquibase.com/commands/flow/flow.html
  #       command: flow
  #       cmdArgs: {flow-file: "./generate-update-info.yaml"}

  liquibaseUpdate:
    # Run Update on Latest Repo State
    # https://docs.liquibase.com/commands/update/update-sql.html
    # actions:
    #   - type: liquibase
    #     command: update-sql
    #     cmdArgs: { }

    # # Run Update on Latest Repo State
    # # https://docs.liquibase.com/commands/update/update.html
    #   - type: liquibase
    #     command: update
    #     cmdArgs: { }

endStage:
  actions:
    # Run Checks on Database
    # https://docs.liquibase.com/commands/quality-checks/subcommands/run.html
    - type: liquibase
      command: checks run
      cmdArgs:
        { checks-scope: "database", 
          checks-settings-file: "s3://${AWS_S3_BUCKET}/static/checks/liquibase.checks-settings.conf",
          verbose: "true"
        }

    # Show history
    # https://docs.liquibase.com/commands/change-tracking/history.html
    - type: liquibase
      command: history
      cmdArgs: {}